name: flask

on:
  push:
    branches:
      - main

jobs:
  save_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Save data to text file
        run: |
          # Python code to save data to a text file
          data = "This is the data to be saved to the file."
          with open("data.txt", "w") as file:
              file.write(data)

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data.txt
          git commit -m "Save data to text file"
          git push
