name: flask

on:
  schedule:
    - cron: "0 */5 * * *"  # Runs every 5 minutes
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true  # Not recommended for production

jobs:
  example:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2.0.0
        with:
          python-version: '3.12.2'
      - name: Create data.txt (optional)  # Uncomment if needed
        run: touch ./data.txt  # Creates the file if it doesn't exist
      - name: Install requirements
        run: pip install -r requirements.txt  # Update with your requirements file
      - name: Run app
        run: python your_script_name.py  # Replace with your actual script name
