name: Bot

on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  API_KEY: ${{ secrets.TOKEN}}

jobs:
  scrape-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.2'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Test env vars for python
        run: TEST_SECRET=${{ secrets.TOKEN }}
      - name: Run Bot
        run: python bot.py
